### ISSUE TITLE
Drive Up- / Download fails

### ISSUE THREAD

**Issue by peat80** [ChernyshovYuriy/OpenRadio#19] opened 2023-09-22 21:52 UTC
On the latest versions i can't use google drive to download or upload my favourite stations anymore.

**Comment by ChernyshovYuriy** [comment] 2023-09-22 23:15
What kind of device you use? Works fine on my Pixel 4.

**Comment by peat80** [comment] 2023-09-22 23:28
Huawai Mate 10 Pro (Android 10)
Nvidia ShieldTV (Android TV 11)

Does not work on both.

**Comment by Dtrieb** [comment] 2023-10-13 10:15
Here on Android 14 Pixel 7 pro the same.
![Screenshot_20231013-121410](https://github.com/ChernyshovYuriy/OpenRadio/assets/3650284/59f1128a-b086-4b8c-b00d-82e209ca3f0f)

**Comment by ChernyshovYuriy** [comment] 2023-10-13 11:03
I tried on many emulators (different android version) and all my android devices and it works.
Can you clean Storage and Cache of the Open Radio app from the Settings menu of the Android System?
If that doesnt help, I might bring back Logs reporting system to get logs from your device.

**Comment by Dtrieb** [comment] 2023-10-13 11:20
Okay clear Storage helps me.

Now I have to try it on my Google TV (Stick)

**Comment by ChernyshovYuriy** [comment] 2023-10-13 11:21
Now, there is an issue with parsing data from Google .. I am working on it :-(

**Comment by Dtrieb** [comment] 2023-10-13 11:27
Okay on my Google TV Stick it didn't work.
![PXL_20231013_112556059~2](https://github.com/ChernyshovYuriy/OpenRadio/assets/3650284/c56de305-6ae5-44ac-bca2-ee511ea70e6f)

**Comment by ChernyshovYuriy** [comment] 2023-10-13 14:39
Parsing of Radios from Google fixed and pushed to review to Google.

**Comment by peat80** [comment] 2023-10-13 17:50
Clearing data of the app fixed the issue for me aswell on both devices. 😎👌

**Comment by ChernyshovYuriy** [comment] 2023-10-14 11:28
Ok, thats good. Can I close this issue then?

**Comment by Dtrieb** [comment] 2023-10-14 12:19
Wait until I get the update on my Google TV Stick and if it's works there too you can close it.

**Comment by Dtrieb** [comment] 2023-10-15 17:21
> Okay on my Google TV Stick it didn't work. ![PXL_20231013_112556059~2](https://user-images.githubusercontent.com/3650284/274887630-c56de305-6ae5-44ac-bca2-ee511ea70e6f.jpg)

Same error after update. 😔

**Comment by 2Ratz** [comment] 2023-10-16 10:41
Same issue on Chromecast HD TV . Phone works fine.

![20231016_104936](https://github.com/ChernyshovYuriy/OpenRadio/assets/143018825/a57873e6-08bd-4cea-b825-ab521e0310c6)

**Comment by ChernyshovYuriy** [comment] 2023-10-16 14:48
Even when clean all cache and data associated with the Open Radio?
I might bring back Logs feature to get logs from the device to understand the issue.

**Comment by 2Ratz** [comment] 2023-10-16 14:59
Yes

Op ma 16 okt. 2023 16:48 schreef Yurii Chernyshov ***@***.***

**Comment by ChernyshovYuriy** [comment] 2023-10-17 22:42
New version of Open radio has option to send logs from General Settings.
Please reproduce issue several times and send the logs. When sent, write here some details so I can identify your email (time, device, maybe what was currently playing, etc ....)

**Comment by 2Ratz** [comment] 2023-10-18 07:00
Already sent one after I find out there was an update before I read the
comment. In my enthousiasme I checked the download from Drive because it
was fixed for the phone.  I will reproduce it several times and sent it
again. European time now 9.00 o clock in the morning.

Op wo 18 okt. 2023 00:42 schreef Yurii Chernyshov ***@***.***

**Comment by 2Ratz** [comment] 2023-10-18 07:10
Sent again 2 logs. Triest several times download and upload from Drive.
Second time forced closing the app and cleared the cache and did it again.
For some reason I had to try several times to open the general menu before
it opend. Email ***@***.*** about 9:05 European time in the morning.

Op wo 18 okt. 2023 08:59 schreef Rick ***@***.***>:

**Comment by Dtrieb** [comment] 2023-10-18 08:06
Send my logs also around 10:00 o'clock.

**Comment by ChernyshovYuriy** [comment] 2023-10-18 10:54
Bad news folks, there are already tickets to Goolge, with resolution **"DRIVE permission is not allowed on Android TV"**.
https://issuetracker.google.com/issues/258598159
https://issuetracker.google.com/issues/267924984

Are you guys sure Google Drive worked before on Android TV ?

**Comment by 2Ratz** [comment] 2023-10-18 11:01
No, I can't confirm that Drive for Open Radio worked on Android TV because
I'm just using it. But as I wrote in another topic, the file manager
(X-plore) that I previously used to transfer files from Drive to Android TV
suddenly stopped working at the beginning of this year for the same reason.

Op wo 18 okt 2023 om 12:54 schreef Yurii Chernyshov <
***@***.***>:

**Comment by peat80** [comment] 2023-10-18 11:14
> Bad news folks, there are already tickets to Goolge, with resolution **"DRIVE permission is not allowed on Android TV"**. https://issuetracker.google.com/issues/258598159 https://issuetracker.google.com/issues/267924984
> 
> Are you guys sure Google Drive worked before on Android TV ?

It worked and works fine for me on shieldtv (Android TV)
I could also install on my bravia tv to test this on Google TV too if that would help.

**Comment by ChernyshovYuriy** [comment] 2023-10-18 11:22
If there is no error shown by Open Radio itself I can't do anything, that's the way Google limit access to GDrive.
![Screenshot from 2023-10-18 07-17-16](https://github.com/ChernyshovYuriy/OpenRadio/assets/931955/f0b69f75-969e-4100-8451-741c99b41319)

**Comment by Dtrieb** [comment] 2023-10-18 11:37
Any other possibilities for exchange stations?

Like QR-Code, Nearby Share or something like that?

**Closed** 2023-10-18 12:10 UTC
Labels: help wanted
